language: php

php:
  - 5.4
  - 5.6

services: mysql

before_script:
  - composer self-update
  - composer install --dev --prefer-dist
  - "mysql -utravis -e 'create database if not exists `laraveltesting_test`;'"
  - php artisan migrate:install
  - php artisan migrate
  - php artisan migrate:install --env=”testing”
  - php artisan serve
  - sleep 5

script:
  - vendor/bin/phpunit
  - vendor/bin/behat
