language: php

php:
  - 5.4
  - 5.6

services: mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - "mysql -utravis -e 'create database if not exists `laraveltesting_test`;'"
  - APP_ENV=testing php artisan serve &
  - sleep 5

script:
  - vendor/bin/phpunit
  - vendor/bin/behat
