language: php
php:
  - 5.4
  - 5.6
before_script:
  - composer self-update
  - composer install
  - "mysql -utravis -e 'create database if not exists `laraveltesting`';'"
script:
  - vendor/bin/phpunit